openapi: 3.0.3
info:
  title: System Rezerwy Federalnej - OpenAPI 3.0
  version: 1.0.0
externalDocs:
  description: Dokumentacja projektu
  url: https://github.com/kijko/fed/wiki
servers:
  - url: https://fed-app.azurewebsites.net/api
tags:
  - name: Uwierzytelnianie
  - name: Zarządzanie użytkownikami
  - name: Zarzadzanie kontem
  - name: Ksiegowanie przelewow
paths:
  /sign-in:
    post:
      tags:
        - Uwierzytelnianie
      summary: Pobierz token sesji
      operationId: signIn
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  example: user123
                password:
                  type: string
                  example: 123456
      responses:
        '200':
          description: 'Zwraca token sesji i inne'
          content:
            application/json:
              schema:
                type: object
                properties:
                  jwt:
                    type: string
                    example: 'eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5NDhjYTYwZS1mOWY1LTQ1ODAtODZjYy1kZjVlZThlZTJhNTciLCJ0eXBlIjoiQURNSU4iLCJleHAiOjE3MDQyMzMzMzd9.ESiH8OoI8Y7Iqhzu6Lhs9HPlyLQ51wgolpIE-uC0OvnQwZk07-SRC3r_fC2IcH2zDm9yj1DCzV88p-ciorpeKQ'
                    description: Token sesji
                  type:
                    type: string
                    example: 'CLIENT'
                    description: Typ użytkownika. "ADMIN", "CLIENT" lub "BANK_EMPLOYEE"
                  expireAt:
                    type: string
                    format: date-time
                    example: '2024-01-02T22:08:57.671092543Z'
                    description: Data i czas wygaśnięcia sesji (strefa czasowa UTC)
  /users:
    get:
      tags:
        - Zarządzanie użytkownikami
      summary: '[ADMIN ONLY] Pobierz listę wszystkich użytkowników'
      operationId: getUsers
      parameters:
        - name: Authorization
          in: header
          description: 'Token sesji w formacie "Bearer {TOKEN}"'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Zwraca liste
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: string
                      example: '582cbb20-dcfa-4ad7-bf73-32f3e9af5299'
                      description: Jednoznaczny identyfikator uzytkownika
                    firstname:
                      type: string
                      example: 'Andrzej'
                      description: Imie usera
                    lastname:
                      type: string
                      example: 'Brzęczyszczykiewicz'
                      description: Nazwisko usera
                    type:
                      type: string
                      example: 'CLIENT'
                      description: Typ użytkownika. "ADMIN", "CLIENT" lub "BANK_EMPLOYEE"
                    blocked:
                      type: boolean
                      example: false
                      description: Flaga mówiąca czy użytkownik jest zablokowany
    post:
      tags:
        - Zarządzanie użytkownikami
      summary: '[ADMIN ONLY] Dodaj usera'
      operationId: addUser
      parameters:
        - name: Authorization
          in: header
          description: 'Token sesji w formacie "Bearer {TOKEN}"'
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  example: endru1
                  description: Login usera
                password:
                  type: string
                  example: 123456
                  description: Haslo usera
                firstname:
                  type: string
                  example: 'Andrzej'
                  description: Imie usera
                lastname:
                  type: string
                  example: 'Brzęczyszczykiewicz'
                  description: Nazwisko usera
                type:
                  type: string
                  example: 'CLIENT'
                  description: Typ użytkownika. "ADMIN", "CLIENT" lub "BANK_EMPLOYEE"
      responses:
        '200':
          description: Zwraca dodanego usera
          content:
            application/json:
              schema:
                type: object
                properties:
                  firstname:
                    type: string
                    example: 'Andrzej'
                    description: Imie usera
                  lastname:
                    type: string
                    example: 'Brzęczyszczykiewicz'
                    description: Nazwisko usera
                  type:
                    type: string
                    example: 'CLIENT'
                    description: Typ użytkownika. "ADMIN", "CLIENT" lub "BANK_EMPLOYEE"
                  blocked:
                    type: boolean
                    example: false
                    description: Flaga mówiąca czy użytkownik jest zablokowany
  /users/{userId}:
    patch:
      tags:
        - Zarządzanie użytkownikami
      summary: '[ADMIN ONLY] Zablokuj usera'
      operationId: patchUser
      parameters:
        - name: Authorization
          in: header
          description: 'Token sesji w formacie "Bearer {TOKEN}"'
          required: true
          schema:
            type: string
        - name: userId
          in: path
          description: ID uzytkownika
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                blocked:
                  type: boolean
                  example: true
      responses:
        '200':
          description: Zwraca zaktualizowanego usera
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: '582cbb20-dcfa-4ad7-bf73-32f3e9af5299'
                    description: Jednoznaczny identyfikator uzytkownika
                  firstname:
                    type: string
                    example: 'Andrzej'
                    description: Imie usera
                  lastname:
                    type: string
                    example: 'Brzęczyszczykiewicz'
                    description: Nazwisko usera
                  type:
                    type: string
                    example: 'CLIENT'
                    description: Typ użytkownika. "ADMIN", "CLIENT" lub "BANK_EMPLOYEE"
                  blocked:
                    type: boolean
                    example: false
                    description: Flaga mówiąca czy użytkownik jest zablokowany
  /account:
    get:
      tags:
        - Zarzadzanie kontem
      summary: '[CLIENT ONLY] Pobierz dane konta zalogowanego użytkownika'
      operationId: getAccount
      parameters:
        - name: Authorization
          in: header
          description: 'Token sesji w formacie "Bearer {TOKEN}"'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Zwraca obiekt konta klienta
          content:
            application/json:
              schema:
                type: object
                properties:
                  accountNumber:
                    type: string
                    description: "28-liczbowy number konta (bez spacji)"
                    example: 1234567890123456789012345678
                  login:
                    type: string
                    description: "Login użytkownika"
                    example: andrew23
                  firstName:
                    type: string
                    description: "Pierwsze imie"
                    example: Jerzy
                  lastName:
                    type: string
                    description: "NAzwisko"
                    example: Brzeczyszczykiweicz
                  balance:
                    type: string
                    description: "stan konta jako string"
                    example: "1.234"
                  outboundTransfers:
                    type: array
                    description: "Przelewy wychodzące"
                    items:
                      properties:
                        amount:
                          type: string
                          description: "Kwota przelewu jako string"
                          example: "5200.532"
                        fromAccountNumber:
                          type: string
                          description: "Numer konta wysyłającego"
                          example: "1234567890123456789012345678"
                        toAccountNumber:
                          type: string
                          description: "Numer konta otrzymujacego"
                          example: "0987654321098765432112345678"
                        requestedAt:
                          type: string
                          format: date-time
                          description: "Data zlecenia przelewu (strefa czasowa UTC!)"
                          example: "2024-01-07T18:47:23.145305Z"
                        status:
                          type: string
                          description: "Stan przelewu. Mozliwe wartosci: APPROVED, REJECTED, PENDING"
                          example: "REJECTED"
                  inboundTransfer:
                    type: array
                    description: "Przelewy przychodzące"
                    items:
                      properties:
                        amount:
                          type: string
                          description: "Kwota przelewu jako string"
                          example: "5200.532"
                        fromAccountNumber:
                          type: string
                          description: "Numer konta wysyłającego"
                          example: "1234567890123456789012345678"
                        toAccountNumber:
                          type: string
                          description: "Numer konta otrzymujacego"
                          example: "0987654321098765432112345678"
                        requestedAt:
                          type: string
                          format: date-time
                          description: "Data zlecenia przelewu (strefa czasowa UTC!)"
                          example: "2024-01-07T18:47:23.145305Z"
                        status:
                          type: string
                          description: "Stan przelewu. Mozliwe wartosci: APPROVED, REJECTED, PENDING"
                          example: "APPROVED"
    post:
      tags:
        - Zarzadzanie kontem
      summary: '[CLIENT ONLY] Przelej kase'
      operationId: sendMoney
      parameters:
        - name: Authorization
          in: header
          description: 'Token sesji w formacie "Bearer {TOKEN}"'
          required: true
          schema:
            type: string
      requestBody:
        description: "Dane przelewu"
        content:
          application/json:
            schema:
              type: object
              properties:
                toAccountNumber:
                  type: string
                  description: "Numer konta odbiorcy"
                  example: "1234567890123456789012345678"
                amount:
                  type: string
                  description: "Kwota przelewu jako string"
                  example: "2.000"
        required: true
      responses:
        '200':
          description: "Przelew poszedl"
        '400':
          description: 'Dane przelewu sie nie zgadzaja'
        '500':
          description: 'Cos poszlo nie tak'
  /transfers:
    get:
      tags:
        - Ksiegowanie przelewow
      summary: '[PRACOWNIK BANKU ONLY] Pobierz liste wszystkich przelewow: do akceptacji, zaakceptowane, odrzucone - w zaleznosci od parametru status'
      operationId: getTransfers
      parameters:
        - name: Authorization
          in: header
          description: 'Token sesji w formacie "Bearer {TOKEN}"'
          required: true
          schema:
            type: string
        - name: status
          in: query
          description: "Filtruj po statusie. Mozliwe wartosci: APPROVED, REJECTED, PENDING"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "lista przelewow"
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: string
                      description: "identyfikator przelewu w formacie UUID"
                      example: "3b514962-8a34-4cd4-ba61-2eb8a2c3b307"
                    sender:
                      type: string
                      description: "Imie i nazwisko wysylajacego"
                      example: "Andrew Leppur"
                    recipient:
                      type: string
                      description: "Imie i nazwisko otrzymujacego"
                      example: "Jerzy Zwierzy"
                    amount:
                      type: string
                      description: "Kwota przelewu"
                      example: "55.223"
                    dateTime:
                      type: string
                      format: date-time
                      description: "Data i czas zelecenia przelewu (UTC!)"
                      example: "2024-01-07T19:47:23.145305Z"
                    status:
                      type: string
                      description: "Status przelewu. Mozliwe wartosci: APPROVED, REJECTED, PENDING"
                      example: "APPROVED"
  /transfers/{transferId}:
    post:
      tags:
        - Ksiegowanie przelewow
      summary: '[PRACOWNIK BANKU ONLY] Zaakceptuj badz odrzuć przelew'
      operationId: performTransfer
      parameters:
        - name: Authorization
          in: header
          description: 'Token sesji w formacie "Bearer {TOKEN}"'
          required: true
          schema:
            type: string
        - name: transferId
          in: path
          description: ID przelewu
          required: true
          schema:
            type: string
      requestBody:
        description: "Status przelewu"
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  description: "status - jedna z dwoch wartosci APPROVED gdy zaakceptowany, REJECTED gdy odrzucony"
                  example: "REJECTED"
        required: true
      responses:
        '200':
          description: "Zwraca liste przelewow do zaakceptowania"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: "identyfikator przelewu w formacie UUID"
                    example: "3b514962-8a34-4cd4-ba61-2eb8a2c3b307"
                  sender:
                    type: string
                    description: "Imie i nazwisko wysylajacego"
                    example: "Andrew Leppur"
                  recipient:
                    type: string
                    description: "Imie i nazwisko otrzymujacego"
                    example: "Jerzy Zwierzy"
                  amount:
                    type: string
                    description: "Kwota przelewu"
                    example: "55.223"
                  dateTime:
                    type: string
                    format: date-time
                    description: "Data i czas zelecenia przelewu (UTC!)"
                    example: "2024-01-07T19:47:23.145305Z"
                  status:
                    type: string
                    description: "Status przelewu. Mozliwe wartosci: APPROVED, REJECTED, PENDING"
                    example: "APPROVED"
