/*
 * This file is generated by jOOQ.
 */
package pl.edu.prz.baw.houston.fed.db;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import pl.edu.prz.baw.houston.fed.db.tables.Account;
import pl.edu.prz.baw.houston.fed.db.tables.FedUser;
import pl.edu.prz.baw.houston.fed.db.tables.TransferRequest;
import pl.edu.prz.baw.houston.fed.db.tables.records.AccountRecord;
import pl.edu.prz.baw.houston.fed.db.tables.records.FedUserRecord;
import pl.edu.prz.baw.houston.fed.db.tables.records.TransferRequestRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> ACCOUNT_PKEY = Internal.createUniqueKey(Account.ACCOUNT, DSL.name("account_pkey"), new TableField[] { Account.ACCOUNT.ACCOUNT_NUMBER }, true);
    public static final UniqueKey<FedUserRecord> FED_USER_PKEY = Internal.createUniqueKey(FedUser.FED_USER, DSL.name("fed_user_pkey"), new TableField[] { FedUser.FED_USER.UUID }, true);
    public static final UniqueKey<TransferRequestRecord> TRANSFER_REQUEST_PKEY = Internal.createUniqueKey(TransferRequest.TRANSFER_REQUEST, DSL.name("transfer_request_pkey"), new TableField[] { TransferRequest.TRANSFER_REQUEST.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AccountRecord, FedUserRecord> ACCOUNT__FK_OWNER = Internal.createForeignKey(Account.ACCOUNT, DSL.name("fk_owner"), new TableField[] { Account.ACCOUNT.OWNER_ID }, Keys.FED_USER_PKEY, new TableField[] { FedUser.FED_USER.UUID }, true);
    public static final ForeignKey<TransferRequestRecord, FedUserRecord> TRANSFER_REQUEST__FK_FINALIZED_BY = Internal.createForeignKey(TransferRequest.TRANSFER_REQUEST, DSL.name("fk_finalized_by"), new TableField[] { TransferRequest.TRANSFER_REQUEST.FINALIZED_BY }, Keys.FED_USER_PKEY, new TableField[] { FedUser.FED_USER.UUID }, true);
    public static final ForeignKey<TransferRequestRecord, AccountRecord> TRANSFER_REQUEST__FK_FROM_ACCOUNT = Internal.createForeignKey(TransferRequest.TRANSFER_REQUEST, DSL.name("fk_from_account"), new TableField[] { TransferRequest.TRANSFER_REQUEST.FROM_ACCOUNT }, Keys.ACCOUNT_PKEY, new TableField[] { Account.ACCOUNT.ACCOUNT_NUMBER }, true);
    public static final ForeignKey<TransferRequestRecord, AccountRecord> TRANSFER_REQUEST__FK_TO_ACCOUNT = Internal.createForeignKey(TransferRequest.TRANSFER_REQUEST, DSL.name("fk_to_account"), new TableField[] { TransferRequest.TRANSFER_REQUEST.TO_ACCOUNT }, Keys.ACCOUNT_PKEY, new TableField[] { Account.ACCOUNT.ACCOUNT_NUMBER }, true);
}
