/*
 * This file is generated by jOOQ.
 */
package pl.edu.prz.baw.houston.fed.db;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import pl.edu.prz.baw.houston.fed.db.tables.Account;
import pl.edu.prz.baw.houston.fed.db.tables.FedUser;
import pl.edu.prz.baw.houston.fed.db.tables.TransferRequest;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account</code>.
     */
    public final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.fed_user</code>.
     */
    public final FedUser FED_USER = FedUser.FED_USER;

    /**
     * The table <code>public.transfer_request</code>.
     */
    public final TransferRequest TRANSFER_REQUEST = TransferRequest.TRANSFER_REQUEST;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Account.ACCOUNT,
            FedUser.FED_USER,
            TransferRequest.TRANSFER_REQUEST
        );
    }
}
