/*
 * This file is generated by jOOQ.
 */
package pl.edu.prz.baw.houston.fed.db;


import pl.edu.prz.baw.houston.fed.db.tables.Account;
import pl.edu.prz.baw.houston.fed.db.tables.FedUser;
import pl.edu.prz.baw.houston.fed.db.tables.TransferRequest;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.fed_user</code>.
     */
    public static final FedUser FED_USER = FedUser.FED_USER;

    /**
     * The table <code>public.transfer_request</code>.
     */
    public static final TransferRequest TRANSFER_REQUEST = TransferRequest.TRANSFER_REQUEST;
}
